---
# tasks file for gitlab
- name: Install dependices
  pip:
    name: docker-py

- name: run GitLab server
  docker_container:
    name: gitlab-ce
    image: gitlab/gitlab-ee
    volumes:
      - /data
    ports:
      - 80:80
      - 443:443

- name: Install PlantUML Server
  docker_container:
    name: PlantUML
    image: plantuml/plantuml-server:tomcat
    #volumes:
    #  - /data
    ports:
      - 8080:8080
